import test from 'node:test';
import assert from 'node:assert/strict';
import {createStudioModes} from '../modes.mjs';
function setup(){let resolve;const ready=new Promise(r=>resolve=r),log=[],active={rig:false,motion:false},notes={draft:[0,.5],camera:28};const view=(id,wait=false)=>({ensure:()=>wait?ready:Promise.resolve(),setActive:value=>{active[id]=value;log.push([id,value]);assert.ok(!(active.rig&&active.motion),'two active renderers');}});const modes=createStudioModes({rig:view('rig'),motion:view('motion',true)});return {modes,resolve,log,active,notes};}
test('studio entry initializes only rig view and pauses inactive authoring',async()=>{const f=setup();await f.modes.select('rig');assert.deepEqual(f.active,{rig:true,motion:false});assert.equal(f.modes.pending,false);});
test('lazy mode switch deactivates current view before waiting and preserves notes/drafts',async()=>{const f=setup(),before=structuredClone(f.notes);await f.modes.select('rig');const pending=f.modes.select('motion');assert.deepEqual(f.active,{rig:false,motion:false});assert.equal(f.modes.pending,true);f.resolve();assert.equal(await pending,true);assert.deepEqual(f.active,{rig:false,motion:true});assert.deepEqual(f.notes,before);});
test('late lazy readiness cannot reactivate a mode after a newer selection',async()=>{const f=setup();await f.modes.select('rig');const pending=f.modes.select('motion');await f.modes.select('rig');f.resolve();assert.equal(await pending,false);assert.deepEqual(f.active,{rig:true,motion:false});});
test('page departure cancels late readiness and bfcache restoration keeps the chosen mode paused until ready',async()=>{const f=setup();await f.modes.select('rig');const pending=f.modes.select('motion');f.modes.suspend();f.resolve();await pending;assert.deepEqual(f.active,{rig:false,motion:false});await f.modes.restore();assert.equal(f.modes.mode,'motion');assert.deepEqual(f.active,{rig:false,motion:true});});
test('permanent disposal rejects further mode activation',async()=>{const f=setup();await f.modes.select('rig');f.modes.dispose();assert.equal(await f.modes.select('motion'),false);assert.deepEqual(f.active,{rig:false,motion:false});});
test('failed authoring initialization leaves the existing rig view available',async()=>{const errors=[],active={};const modes=createStudioModes({rig:{ensure:async()=>{},setActive:v=>active.rig=v},motion:{ensure:async()=>{throw Error('unavailable');},setActive:v=>active.motion=v},report:e=>errors.push(e.message)});await modes.select('rig');assert.equal(await modes.select('motion'),false);assert.deepEqual(active,{rig:true,motion:false});assert.equal(modes.mode,'rig');assert.deepEqual(errors,['unavailable']);});

test('renderer activation failure stays suspended and reports without an unhandled fallback rejection',async()=>{const errors=[],modes=createStudioModes({rig:{ensure:async()=>{},setActive:v=>{if(v)throw Error('graphics unavailable');}},motion:{ensure:async()=>{},setActive:()=>{}},report:e=>errors.push(e.message)});assert.equal(await modes.select('rig'),false);assert.equal(modes.pending,false);assert.equal(errors.length,2);});
