import {modelReviewGroup,validateFamilyMapping,familyHierarchyRows,actualStudioOverlay,evaluatedFamilyContacts,familyContactLayers,resolveFamilyMapping} from './family.mjs';
import {LIMITS,deform,motionClips,quaternionEuler,euler,clamp,point,RenderClock} from './core.mjs';
import {StudioRenderer} from './renderer.mjs';
import {AtomicAssetStore,InspectionGate,prepareAsset,verifyCandidateCompatibility,resolvePairedClip,evaluateInspection,hierarchyRows,skeletonOverlay,selectedNodeInfo,paletteMembership,weightGeometry,areaAudit,areaGeometry,flaggedTriangleLines,authorizePriorMovement,actorPlacement,placedGeometry,placedSkeleton,placedNodeInfo,placedLines,deriveSoleDefinition,evaluatedSoles,soleMarkerLayers} from './inspection.mjs';
const ui$=id=>document.getElementById(id),inspectorBundle=JSON.parse(ui$('bundle-data').textContent);
const assetStore=new AtomicAssetStore(),preparedAssets=new Map();let inspectorRenderer=null,inspectorClock=null,selectedNode=0,currentTime=0,localEdits={},currentClipId='rest',posePin=null,flaggedCase=null,viewRevision=0,viewCache=null,importMotionGeneration=0;
let inspectorCamera={yaw:28,pitch:12,span:2.15,center:[0,.86,0]};
let inspectorInitialized=false,inspectorDisposed=false;const notesByModel=new Map();
const resourceGates={focus:document.hasFocus(),page:!document.hidden,intersection:true,context:true,mode:true,host:true};
const inspectorGate=new InspectionGate(resourceGates,{resume:()=>inspectorClock?.resume(),suspend:reason=>inspectorClock?.suspend(reason)});
const currentAsset=()=>assetStore.current;
const reportInspector=(text,error=false)=>{ui$(error?'error':'message').textContent=text;};
const decodeAsset=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const hashBytes=async bytes=>{if(!globalThis.crypto?.subtle)throw Error('This browser cannot verify import hashes. The current asset was retained.');return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');};
const activeClip=()=>currentAsset()?.clips.find(c=>c.id===currentClipId)||null;
const activeStatic=()=>currentAsset()?.staticPoses.find(p=>p.id===currentClipId)||null;
const clipDuration=()=>activeClip()?.duration||0;
const movementPermissions=new WeakMap(),soleDefinitions=new WeakMap();
function permissionFor(a,clip){if(!clip)return null;if(!movementPermissions.has(clip))movementPermissions.set(clip,authorizePriorMovement(a,clip,inspectorBundle.motion.document,inspectorBundle.motion));return movementPermissions.get(clip);}
function currentPermission(){return Object.keys(localEdits).length?null:permissionFor(currentAsset(),activeClip());}
function currentPlacement(){const permission=currentPermission();return actorPlacement(permission,currentTime,ui$('travelProof').checked&&!!permission);}
function refreshProofControls(){
 const permission=currentPermission();for(const id of ['travelProof','soleMarkers']){ui$(id).disabled=!permission;if(!permission)ui$(id).checked=false;}
 ui$('loop').disabled=!activeClip()||ui$('travelProof').checked;
 if(ui$('travelProof').checked)ui$('loop').checked=false;
 ui$('movementInfo').textContent=permission?'Optional prior-original reference-speed straight-level proof. Travel = +Z '+permission.referenceSpeed+' x clamped seconds; one cycle. Green sole polygon: authored contact interval; orange: swing. Six actual points per foot; no quality acceptance.':'Reference travel and sole markers require the exact prior human clip with no inspection overrides. Imported/unreviewed motion receives no guessed speed or marker authorization.';
}
function candidatePairingAllowed(){if(!ui$('reviewOptIn').checked)return false;const a=currentAsset(),c=activeClip();if(!a||!preparedAssets.has('human01_skin_candidate_v1')||!(a.record.id==='human01'||a.compatibility)||activeStatic())return false;if(!c)return currentClipId==='rest';return c.id.startsWith('prior:')&&c.classification==='prior-original'&&c.sourceHash===inspectorBundle.motion.sha256||c.id.startsWith('embedded:')&&c.classification==='existing-diagnostic'&&c.sourceHash===a.record.sha256;}
function pauseInspector(reason='Paused'){inspectorClock?.stop(reason);ui$('play').textContent='Play';}
function invalidateInspector(){viewRevision++;viewCache=null;inspectorClock?.request();}
function setResourceGate(key,value,reason){const wasOpen=inspectorGate.open;inspectorGate.set(key,value,reason);if(!wasOpen&&inspectorGate.open&&inspectorClock)reportInspector('Viewer ready. Playback remains paused until Play.');}
function syncInputFocus(){setResourceGate('focus',document.hasFocus(),'Paused while unfocused');setResourceGate('page',!document.hidden,'Paused while hidden');}
function inspectorOption(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function recordAllowed(record){return (record.activeBindingAllowed!==false||record.requiresReviewOptIn)&&(!record.requiresReviewOptIn||ui$('reviewOptIn').checked);}
function assertReviewAllowed(record){if(record.activeBindingAllowed===false&&!record.requiresReviewOptIn)throw Error('Source is on hold; revised accepted hash and contract required');if(record.requiresReviewOptIn&&!ui$('reviewOptIn').checked)throw Error('Explicit proposed-candidate opt-in is required');}
function refreshReviewPolicy(){for(const option of Array.from(ui$('asset').options)){const record=inspectorBundle.records.find(r=>r.id===option.value)||inspectorBundle.candidate;if(record.id===option.value)option.disabled=!recordAllowed(record);}}
function fillAssetMenu(){const groups=new Map();for(const record of inspectorBundle.records){const label=modelReviewGroup(record);if(!groups.has(label)){const group=document.createElement('optgroup');group.label=label;groups.set(label,group);}const option=inspectorOption(record.id,record.label+' / '+record.version+(record.activeBindingAllowed===false?' / held - unavailable':''));option.disabled=!recordAllowed(record);groups.get(label).append(option);}ui$('asset').replaceChildren(...groups.values());}
function refreshTree(){
 const a=currentAsset(),filter=ui$('search').value.toLowerCase();ui$('tree').replaceChildren(...a.rows.filter(r=>!filter||r.name.toLowerCase().includes(filter)||String(r.id)===filter).map(r=>{const b=document.createElement('button');b.className='node '+r.kind+(r.id===selectedNode?' selected':'');b.style.paddingLeft=(8+r.depth*12)+'px';b.title='Node '+r.id+' · '+r.name+' · '+r.kind+' · '+r.palettes.map(x=>'skin '+x.skinIndex+'/palette '+x.paletteIndex).join(', ');b.textContent=r.id+' '+r.name+' ['+r.kind+']';b.onclick=()=>{selectedNode=r.id;refreshTree();refreshSelection();invalidateInspector();};return b;}));
}
function refreshSource(){
 const r=currentAsset().record;ui$('readiness').textContent=modelReviewGroup(r)+' / '+r.version;
 ui$('rigStats').textContent=currentAsset().model.nodes.length+' nodes / '+currentAsset().model.skins.reduce((n,v)=>n+v.joints.length,0)+' skin joints / '+currentAsset().rows.filter(v=>v.kind==='socket').length+' sockets / markers';
 ui$('loadMotion').disabled=r.sha256!=='eef773e568c1fda0713481e068e7d7eeb1a6f876abe65d793ac5650138befa67';
 const family=resolveFamilyMapping(currentAsset());ui$('familyContacts').disabled=!family;if(!family)ui$('familyContacts').checked=false;ui$('familyInfo').textContent=family?family.family+' / mapped '+Object.keys(family.contacts).join(', ')+' / delivered diagnostics only':'Actual exported hierarchy; family contacts require a matching pinned mapping.';

 const {data,...info}=r;ui$('sourceInfo').textContent=JSON.stringify({...info,inspectorVerifiedCompatibility:currentAsset().compatibility||null,registry:inspectorBundle.registry,catalog:inspectorBundle.catalog},null,2);
 const humanCompatible=r.sha256==='eef773e568c1fda0713481e068e7d7eeb1a6f876abe65d793ac5650138befa67'||!!currentAsset().compatibility;
 for(const id of ['walkProof','walkFlag','runFlag'])ui$(id).disabled=!humanCompatible;
 for(const id of ['candidateProof','candidateOption'])ui$(id).disabled=!ui$('reviewOptIn').checked||!humanCompatible||!preparedAssets.has('human01_skin_candidate_v1');
}
function refreshClipMenu(){
 const a=currentAsset();ui$('clip').replaceChildren(inspectorOption('rest','Bind / rest — no animation'),...a.staticPoses.map(p=>inspectorOption(p.id,p.name+' · existing static diagnostic')),...a.clips.map(c=>inspectorOption(c.id,c.name+' · '+c.classification)));
 ui$('clip').value=currentClipId;refreshTimeline();
}
function refreshTimeline(){
 const canPair=candidatePairingAllowed();for(const id of ['candidateProof','candidateOption'])ui$(id).disabled=!canPair;if(ui$('compare').value==='candidate'&&!canPair)ui$('compare').value='off';
 const c=activeClip(),s=activeStatic(),d=clipDuration();ui$('clipInfo').textContent=c?c.classification+' / '+d+' seconds':s?'Static diagnostic pose / no timeline':'Rest pose / playback is available only for delivered clips.';
 for(const id of ['play','scrub','seconds','phase','stepBack','stepForward','loop','speed'])ui$(id).disabled=!c;
 ui$('scrub').max=d||1;ui$('seconds').max=d||1;ui$('loop').checked=!!c?.loop;
 for(const side of ['left','right']){ui$(side+'Lane').replaceChildren(...(c?.contacts?.[side]||[]).map(([start,end])=>{const el=document.createElement('i');el.style.left=(start/d*100)+'%';el.style.width=((end-start)/d*100)+'%';return el;}));}
 ui$('contactInfo').textContent=(c?.contacts?.left?.length||c?.contacts?.right?.length)?'Prior authored contact intervals, in seconds. No world contact solve.':'No authored contact schedule for this selection.';
 refreshProofControls();
}
function currentEvaluatedPose(){return evaluateInspection(currentAsset().model,activeClip(),currentTime,activeStatic()?.pose,localEdits);}
function refreshSelection(){
 const a=currentAsset(),pose=currentEvaluatedPose(),info=placedNodeInfo(selectedNodeInfo(a.model,pose,selectedNode,activeClip(),activeStatic()?.pose,localEdits),currentPlacement());info.kind=a.rows.find(r=>r.id===selectedNode)?.kind||info.kind;ui$('selectedName').textContent=info.name;ui$('selectedSummary').textContent='Node '+info.nodeIndex+' / '+info.kind+' / parent '+(info.parentName??'none')+' / '+info.palette.map(p=>'skin '+p.skinIndex+', palette '+p.paletteIndex).join('; ');ui$('nodeInfo').textContent=JSON.stringify(info,null,2);ui$('writers').textContent=JSON.stringify(info.writtenChannels,null,2);
 const canEdit=info.palette.length>0&&!a.model.nodes[selectedNode].matrix,angles=quaternionEuler(pose.nodes[selectedNode].rotation);
 for(const [prefix,values] of [['pos',pose.nodes[selectedNode].position],['rot',angles],['scale',pose.nodes[selectedNode].scale]])for(let k=0;k<3;k++){const el=ui$(prefix+'XYZ'[k]);el.disabled=!canEdit;if(document.activeElement!==el)el.value=Number(values[k].toFixed(6));}
 ui$('applyEdit').disabled=!canEdit;ui$('clearJoint').disabled=!localEdits[selectedNode];ui$('editInfo').textContent=Object.keys(localEdits).length+' inspection-only joint overrides active.';
}
function fitInspector(){
 const g=currentAsset().bindGeometry,positions=g.flatMap(x=>Array.from(x.positions));let low=[Infinity,Infinity,Infinity],high=[-Infinity,-Infinity,-Infinity];for(let i=0;i<positions.length;i+=3)for(let k=0;k<3;k++){low[k]=Math.min(low[k],positions[i+k]);high[k]=Math.max(high[k],positions[i+k]);}
 const permission=currentPermission();if(ui$('travelProof').checked&&permission)high[2]+=permission.referenceSpeed*permission.duration;
 inspectorCamera.center=low.map((v,k)=>(v+high[k])/2);inspectorCamera.span=Math.max(.15,...low.map((v,k)=>high[k]-v))*1.5;invalidateInspector();
}
function viewFromPose(pose,caption,a=currentAsset(),clip=activeClip(),time=currentTime,placementOverride=null,proofEligible=true){
 const geometry=deform(a.model,pose),audit=areaAudit(a.model,geometry,a.bindGeometry);let shown=ui$('weights').checked?weightGeometry(a.model,geometry,selectedNode):geometry;if(ui$('areas').checked)shown=areaGeometry(shown,audit);
 const permission=!proofEligible||Object.keys(localEdits).length?null:permissionFor(a,clip),placement=placementOverride||actorPlacement(permission,time,ui$('travelProof').checked&&!!permission);let soles=null;
 if(ui$('soleMarkers').checked&&permission&&pose!==a.bind){if(!soleDefinitions.has(a))soleDefinitions.set(a,deriveSoleDefinition(a.model));soles=evaluatedSoles(soleDefinitions.get(a),placedGeometry(geometry,placement),clip,time);}
 const familyContacts=ui$('familyContacts').checked?evaluatedFamilyContacts(a,geometry,placement):null;
 return {geometry:ui$('mesh').checked?placedGeometry(shown,placement):[],overlay:placedSkeleton(actualStudioOverlay(a,pose,selectedNode,{joints:ui$('skeleton').checked,sockets:ui$('sockets').checked}),placement),familyContacts,flaggedLines:placedLines(flaggedCase?flaggedTriangleLines(geometry,flaggedCase.primitive,flaggedCase.triangle):[],placement),soleMarkers:[...soleMarkerLayers(soles),...familyContactLayers(familyContacts)],soles,placement,pose,audit,caption:caption+(placement.enabled?' | +Z '+placement.translation[2].toFixed(6)+' reference travel':' | in place')};
}
function inspectorViews(){
 if(viewCache?.revision===viewRevision)return viewCache.views;
 const a=currentAsset(),current=viewFromPose(currentEvaluatedPose(),(activeClip()?.name||activeStatic()?.name||'Bind')+' @ '+currentTime.toFixed(6)+' s');let views=[current];
 if(ui$('compare').value==='bind')views=[viewFromPose(a.bind,'Bind / rest'),current];
 if(ui$('compare').value==='pin'&&posePin)views=[viewFromPose(posePin.pose,posePin.caption,a,posePin.clip,posePin.seconds,posePin.placement,posePin.proofEligible),current];
 if(ui$('compare').value==='candidate'&&candidatePairingAllowed()){
  views=['human01','human01_skin_candidate_v1'].map(id=>{const paired=preparedAssets.get(id),clip=resolvePairedClip(a,paired,activeClip(),inspectorBundle.motion.sha256);return viewFromPose(evaluateInspection(paired.model,clip||null,currentTime,null,localEdits),(id==='human01'?'Frozen original':'PROPOSED skin candidate')+' · '+(clip?.name||'Bind')+' @ '+currentTime.toFixed(6)+' s',paired,clip);});
 }
 viewCache={revision:viewRevision,views};return views;
}
function drawInspector(dt){
 if(!inspectorRenderer||inspectorDisposed||!Object.values(resourceGates).every(Boolean))return;
 if(dt&&activeClip()){currentTime+=dt*Number(ui$('speed').value);if(currentTime>=clipDuration()){if(ui$('loop').checked&&!ui$('travelProof').checked)currentTime%=clipDuration();else{currentTime=clipDuration();pauseInspector('Clip reached end');}}viewRevision++;viewCache=null;}
 const started=performance.now(),views=inspectorViews(),err=inspectorRenderer.draw({views,camera:inspectorCamera,grid:ui$('grid').checked,skeleton:ui$('skeleton').checked||ui$('sockets').checked,xray:ui$('xray').checked,wire:ui$('wire').checked,foot:false});
 if(err){pauseInspector('Rendering error');reportInspector('WebGL error '+err+'. CPU source evidence remains available.',true);}
 ui$('viewLabels').replaceChildren(...views.map(v=>{const span=document.createElement('span');span.textContent=v.caption;return span;}));
 ui$('movementData').textContent=JSON.stringify(views.map(v=>({view:v.caption,actorWrapper:v.placement,soles:v.soles,mappedActualContacts:v.familyContacts})),null,2);
 ui$('scrub').value=currentTime;ui$('seconds').value=currentTime.toFixed(6);ui$('phase').value=(clipDuration()?currentTime/clipDuration():0).toFixed(6);ui$('timecode').textContent=Math.round(currentTime*30)+' samples at 30 Hz';
 const audit=views.at(-1).audit,count=audit.reduce((s,v)=>s+v.flagged.length,0);ui$('areaInfo').textContent=(ui$('compare').value==='candidate'?views.map(v=>v.caption.split(' · ')[0]+': '+v.audit.reduce((s,x)=>s+x.flagged.length,0)+' flags'+(flaggedCase?', triangle '+flaggedCase.triangle+' ratio '+v.audit[flaggedCase.primitive].ratios[flaggedCase.triangle].toFixed(6):'')).join(' | '):count+' triangles outside 0.5–2× bind area. '+(flaggedCase?'Pinned review: triangle '+flaggedCase.triangle+'; ratio '+audit[flaggedCase.primitive].ratios[flaggedCase.triangle].toFixed(6)+'. ':''))+' Area screening only.';
 ui$('performance').textContent=(inspectorClock.playing?'Playing':'Paused')+' / '+inspectorRenderer.canvas.width+' x '+inspectorRenderer.canvas.height;
 refreshSelection();
}
function seekInspector(t){pauseInspector('Timeline scrubbed');currentTime=clamp(Number(t)||0,0,clipDuration());invalidateInspector();refreshSelection();}
function chooseClip(id){if(id!=='rest'&&!currentAsset()?.clips.some(c=>c.id===id)&&!currentAsset()?.staticPoses.some(p=>p.id===id)){reportInspector('Unknown clip; previous pose retained.',true);return;}pauseInspector('Selection changed');currentClipId=id;currentTime=0;localEdits={};flaggedCase=null;refreshClipMenu();refreshSelection();invalidateInspector();}
function playInspector(){if(inspectorClock.playing){pauseInspector();return;}if(!activeClip())return;if(!Object.values(resourceGates).every(Boolean)){reportInspector('Playback is paused while the viewer is hidden or unfocused.');return;}if(currentTime>=clipDuration())currentTime=0;inspectorClock.play();ui$('play').textContent='Pause';}
async function chooseAsset(id){
 const requested=preparedAssets.get(id)?.record||inspectorBundle.records.find(r=>r.id===id);try{if(requested)assertReviewAllowed(requested);}catch(error){if(currentAsset())ui$('asset').value=currentAsset().record.id;reportInspector('Load failed; previous asset retained. '+error.message,true);return;}
 const generation=assetStore.begin();pauseInspector('Loading asset');++importMotionGeneration;
 try{let prepared=preparedAssets.get(id);if(!prepared){const record=inspectorBundle.records.find(r=>r.id===id);if(!record)throw Error('Unknown bundled asset');const bytes=decodeAsset(record.data),hash=await hashBytes(bytes);if(hash!==record.sha256)throw Error('Bundled asset hash mismatch');prepared=prepareAsset(bytes,record,inspectorBundle.motion.document,inspectorBundle.motion);validateFamilyMapping(prepared);prepared.rows=familyHierarchyRows(prepared);preparedAssets.set(id,prepared);}
  if(currentAsset())notesByModel.set(currentAsset().record.id,ui$('notes').value);if(!assetStore.commit(generation,prepared))return;ui$('notes').value=notesByModel.get(id)||'';prunePreparedAssets();selectedNode=prepared.rows.find(r=>r.kind==='joint')?.id||0;currentClipId='rest';currentTime=0;localEdits={};posePin=null;flaggedCase=null;ui$('compare').value='off';ui$('asset').value=id;reportInspector('',true);refreshSource();refreshTree();ui$('tree').scrollTop=0;refreshClipMenu();refreshSelection();fitInspector();reportInspector(prepared.record.label+' / '+prepared.clips.length+' delivered clips');
 }catch(e){if(generation===assetStore.generation){if(currentAsset())ui$('asset').value=currentAsset().record.id;reportInspector('Load failed; previous asset retained. '+e.message,true);}}
}
async function importAsset(file){
 if(!file)return;const generation=assetStore.begin();pauseInspector('Importing separate GLB');++importMotionGeneration;
 try{if(file.size>LIMITS.bytes)throw Error('GLB exceeds 64 MiB');const bytes=new Uint8Array(await file.arrayBuffer()),hash=await hashBytes(bytes),pinnedRecord=[...inspectorBundle.records,inspectorBundle.candidate].find(r=>r.sha256===hash);if(pinnedRecord)assertReviewAllowed(pinnedRecord);const record={id:'import:'+hash,stableId:'unregistered-private-import',label:file.name,version:'sha256:'+hash.slice(0,12),family:'unreviewed',role:'private_import',sha256:hash,bytes:bytes.length,relativeSource:file.name,visualSourceStatus:'unreviewed_import',rigProductionAcceptance:'not_claimed',collection:'separate_import',readiness:{visual_acceptance:'unreviewed',gameplay_ready:false,runtime_integration:'unverified'},limits:['No compatibility or production acceptance inferred from matching joint names.'],staticPoses:null},prepared=prepareAsset(bytes,record);
  if(generation!==assetStore.generation)return;if(currentAsset())notesByModel.set(currentAsset().record.id,ui$('notes').value);if(!assetStore.commit(generation,prepared))return;ui$('notes').value=notesByModel.get(record.id)||'';for(const key of preparedAssets.keys())if(key.startsWith('import:'))preparedAssets.delete(key);for(const option of Array.from(ui$('asset').options))if(option.value.startsWith('import:'))option.remove();preparedAssets.set(record.id,prepared);prunePreparedAssets();reportInspector('',true);ui$('asset').append(inspectorOption(record.id,file.name+' · separate import'));selectedNode=prepared.rows.find(r=>r.kind==='joint')?.id||0;currentClipId='rest';currentTime=0;localEdits={};posePin=null;flaggedCase=null;ui$('compare').value='off';ui$('asset').value=record.id;refreshSource();refreshTree();refreshClipMenu();refreshSelection();fitInspector();reportInspector('Imported separate asset; original bundled bytes remain frozen. Previous unregistered import was released.');
 }catch(e){if(generation===assetStore.generation)reportInspector('Import failed; previous asset retained. '+e.message,true);}
}
async function importMotion(file){
 if(!file)return;const generation=++importMotionGeneration,a=currentAsset();pauseInspector('Importing motion');
 try{if(file.size>8*1024*1024)throw Error('Motion JSON exceeds 8 MiB');if(a.record.sha256!=='eef773e568c1fda0713481e068e7d7eeb1a6f876abe65d793ac5650138befa67')throw Error('Separate human motion requires exact frozen Human01. A revised rig needs explicit compatibility review.');
  const bytes=new Uint8Array(await file.arrayBuffer()),hash=await hashBytes(bytes),doc=JSON.parse(new TextDecoder().decode(bytes));const prior=hash===inspectorBundle.motion.sha256;
  if(!prior&&doc.rigGlbSha256!==a.record.sha256)throw Error('New human motion must declare rigGlbSha256 matching the loaded frozen rig.');
  const next=motionClips(doc,a.model).map((c,i)=>({...c,id:'import-motion:'+hash+':'+i,classification:prior?'prior-original':'separate-import-unreviewed',sourceHash:hash,source:file.name}));
  if(generation!==importMotionGeneration||a!==currentAsset())return;const combined=[...a.clips.filter(c=>!c.id.startsWith('import-motion:')),...next];if(combined.length>LIMITS.clips)throw Error('Combined clip limit exceeded');a.clips=combined;chooseClip(next[0].id);reportInspector('Loaded '+next.length+' separate motion clips with source SHA-256 '+hash+'.');
 }catch(e){if(generation===importMotionGeneration)reportInspector('Motion import failed; previous clips retained. '+e.message,true);}
}
function proofCase(name,time,triangle=null){
 const clip=currentAsset().clips.find(c=>c.classification==='prior-original'&&c.name===name);if(!clip)return;const comparing=ui$('compare').value==='candidate';chooseClip(clip.id);currentTime=time;ui$('compare').value=comparing?'candidate':'bind';ui$('skeleton').checked=true;ui$('xray').checked=true;ui$('mesh').checked=true;ui$('areas').checked=triangle!==null;flaggedCase=triangle===null?null:{primitive:0,triangle};invalidateInspector();reportInspector('Exact prior-original '+name+' @ '+time+' s. Human GLB and prior motion remain untouched.');
}
function projectDot(position,pane,panes){const cv=ui$('view'),width=cv.clientWidth/panes,height=cv.clientHeight,a=inspectorCamera.yaw*Math.PI/180,p=inspectorCamera.pitch*Math.PI/180,t=position.map((v,k)=>v-inspectorCamera.center[k]),x=Math.cos(a)*t[0]+Math.sin(a)*t[2],z=-Math.sin(a)*t[0]+Math.cos(a)*t[2],y=Math.cos(p)*t[1]-Math.sin(p)*z;return [pane*width+width/2+x*height/inspectorCamera.span,height/2-y*height/inspectorCamera.span];}
function pickInspector(clientX,clientY){if(!ui$('skeleton').checked&&!ui$('sockets').checked)return;const box=ui$('view').getBoundingClientRect(),views=inspectorViews(),x=clientX-box.left,y=clientY-box.top,pane=Math.min(views.length-1,Math.floor(x/(box.width/views.length)));let nearest=null,distance=14;for(const row of currentAsset().rows){if(row.kind==='mesh'||(row.kind==='socket'?!ui$('sockets').checked:!ui$('skeleton').checked))continue;const p=projectDot(point(views[pane].placement.matrix,views[pane].pose.world[row.id].slice(12,15)),pane,views.length),d=Math.hypot(p[0]-x,p[1]-y);if(d<distance){nearest=row.id;distance=d;}}if(nearest!==null){selectedNode=nearest;refreshTree();refreshSelection();invalidateInspector();}}
function exportInspectorReview(){const payload={schema:'private-rig-inspection-review/1',source:currentAsset().record.sha256,assetId:currentAsset().record.stableId,version:currentAsset().record.version,clip:activeClip()?{name:activeClip().name,classification:activeClip().classification,sha256:activeClip().sourceHash}:null,staticDiagnostic:activeStatic()?.name||null,seconds:currentTime,phase:clipDuration()?currentTime/clipDuration():0,selectedNode:placedNodeInfo(selectedNodeInfo(currentAsset().model,currentEvaluatedPose(),selectedNode,activeClip(),activeStatic()?.pose,localEdits),currentPlacement()),referenceProof:{permission:currentPermission(),placement:currentPlacement(),markers:ui$('soleMarkers').checked},inspectionOnlyOverrides:localEdits,camera:inspectorCamera,notes:ui$('notes').value,productionAcceptance:false};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='private-rig-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function installInspectorEvents(){
 ui$('reviewOptIn').onchange=()=>{pauseInspector('Review policy changed');refreshReviewPolicy();if(!ui$('reviewOptIn').checked){ui$('compare').value='off';if(currentAsset().record.requiresReviewOptIn){chooseAsset('human01');return;}}refreshSource();refreshTimeline();invalidateInspector();};ui$('asset').onchange=()=>chooseAsset(ui$('asset').value);ui$('search').oninput=refreshTree;ui$('clip').onchange=()=>chooseClip(ui$('clip').value);ui$('play').onclick=playInspector;
 ui$('scrub').oninput=()=>seekInspector(ui$('scrub').value);ui$('seconds').onchange=()=>seekInspector(ui$('seconds').value);ui$('phase').onchange=()=>seekInspector(clamp(Number(ui$('phase').value)||0,0,1)*clipDuration());ui$('stepBack').onclick=()=>seekInspector(currentTime-1/30);ui$('stepForward').onclick=()=>seekInspector(currentTime+1/30);
 for(const id of ['mesh','skeleton','sockets','xray','weights','areas','wire','grid','compare','familyContacts'])ui$(id).onchange=invalidateInspector;
 for(const id of ['travelProof','soleMarkers'])ui$(id).onchange=()=>{pauseInspector('Reference proof mode changed');refreshTimeline();refreshSelection();fitInspector();invalidateInspector();};
 ui$('fit').onclick=fitInspector;ui$('rest').onclick=()=>chooseClip('rest');document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>{const [yaw,pitch]={front:[0,0],side:[90,0],rear:[180,0],three:[28,12]}[b.dataset.camera];inspectorCamera.yaw=yaw;inspectorCamera.pitch=pitch;invalidateInspector();});
 ui$('pin').onclick=()=>{posePin={pose:structuredClone(currentEvaluatedPose()),proofEligible:Object.keys(localEdits).length===0,seconds:currentTime,clip:activeClip(),placement:structuredClone(currentPlacement()),caption:'Pinned '+(activeClip()?.name||activeStatic()?.name||'Bind')+' @ '+currentTime.toFixed(6)+' s'};ui$('compare').value='pin';invalidateInspector();};
 ui$('applyEdit').onclick=()=>{pauseInspector('Editing inspection pose');try{const edit={position:['X','Y','Z'].map(k=>Number(ui$('pos'+k).value)),rotation:euler(['X','Y','Z'].map(k=>Number(ui$('rot'+k).value))),scale:['X','Y','Z'].map(k=>Number(ui$('scale'+k).value))},next={...localEdits,[selectedNode]:edit};evaluateInspection(currentAsset().model,activeClip(),currentTime,activeStatic()?.pose,next);localEdits=next;refreshProofControls();invalidateInspector();refreshSelection();}catch(e){reportInspector(e.message,true);}};
 ui$('clearJoint').onclick=()=>{delete localEdits[selectedNode];refreshProofControls();refreshSelection();invalidateInspector();};ui$('clearEdits').onclick=()=>{localEdits={};refreshProofControls();refreshSelection();invalidateInspector();};
 ui$('walkProof').onclick=async()=>{if(currentAsset().record.id!=='human01')await chooseAsset('human01');proofCase('walk_original',0);};ui$('walkFlag').onclick=()=>proofCase('walk_original',.9612,276);ui$('runFlag').onclick=()=>proofCase('run_original',.1128,164);
 ui$('candidateProof').onclick=()=>{pauseInspector('Comparing proposed skin');if(!activeClip()&&!activeStatic())proofCase('walk_original',0);ui$('compare').value='candidate';invalidateInspector();};
 ui$('loadAsset').onclick=()=>ui$('assetFile').click();ui$('assetFile').onchange=()=>{const pending=importAsset(ui$('assetFile').files[0]);ui$('assetFile').value='';return pending;};ui$('loadMotion').onclick=()=>ui$('motionFile').click();ui$('motionFile').onchange=()=>{const pending=importMotion(ui$('motionFile').files[0]);ui$('motionFile').value='';return pending;};ui$('exportNotes').onclick=exportInspectorReview;
 document.addEventListener('pointerdown',()=>{syncInputFocus();inspectorClock.touch();},{passive:true});document.addEventListener('keydown',()=>{syncInputFocus();inspectorClock.touch();});document.addEventListener('focusin',syncInputFocus);
 document.querySelectorAll('.editgrid input').forEach(input=>input.onfocus=()=>pauseInspector('Editing inspection pose'));
 const cv=ui$('view');let drag=null;cv.onpointerdown=e=>{cv.focus({preventScroll:true});drag={x:e.clientX,y:e.clientY,yaw:inspectorCamera.yaw,pitch:inspectorCamera.pitch,center:inspectorCamera.center.slice(),pan:e.shiftKey,moved:false};cv.setPointerCapture(e.pointerId);};
 cv.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)<4&&!drag.moved)return;drag.moved=true;if(drag.pan){const scale=inspectorCamera.span/cv.clientHeight;inspectorCamera.center=[drag.center[0]-dx*scale,drag.center[1]+dy*scale,drag.center[2]];}else{inspectorCamera.yaw=drag.yaw+dx*.4;inspectorCamera.pitch=clamp(drag.pitch+dy*.25,-75,75);}invalidateInspector();};
 cv.onpointerup=e=>{if(drag&&!drag.moved)pickInspector(e.clientX,e.clientY);drag=null;};cv.onpointercancel=cv.onlostpointercapture=()=>drag=null;
 cv.addEventListener('wheel',e=>{e.preventDefault();syncInputFocus();inspectorClock.touch();inspectorCamera.span=clamp(inspectorCamera.span*(1+e.deltaY*.001),.05,20);invalidateInspector();},{passive:false});
 document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if([' ','ArrowLeft','ArrowRight'].includes(e.key))e.preventDefault();if(e.key===' ')playInspector();if(e.key==='ArrowLeft')seekInspector(currentTime-1/30);if(e.key==='ArrowRight')seekInspector(currentTime+1/30);if(e.key==='f'||e.key==='F')fitInspector();if(e.key==='r'||e.key==='R')chooseClip('rest');if(e.key==='Escape')pauseInspector();});
 window.addEventListener('blur',()=>setResourceGate('focus',false,'Paused on blur'));window.addEventListener('focus',syncInputFocus);document.addEventListener('visibilitychange',syncInputFocus);
 new ResizeObserver(()=>inspectorClock.request()).observe(cv);if('IntersectionObserver' in window)new IntersectionObserver(entries=>setResourceGate('intersection',entries[0].isIntersecting,'Paused offscreen')).observe(cv);
 cv.addEventListener('webglcontextlost',e=>{e.preventDefault();setResourceGate('context',false,'Context lost');reportInspector('WebGL context lost. Reload this page to resume.',true);});window.addEventListener('pagehide',()=>{setResourceGate('host',false,'Returned to Lab');assetStore.begin();++importMotionGeneration;releaseInspectorRenderer();});window.addEventListener('pageshow',event=>{if(event.persisted){inspectorDisposed=false;resourceGates.focus=document.hasFocus();resourceGates.page=!document.hidden;restoreInspectorRenderer();setResourceGate('host',true);}});
}
async function initializeInspector(){
 try{const motionBytes=decodeAsset(inspectorBundle.motion.data);if(await hashBytes(motionBytes)!==inspectorBundle.motion.sha256)throw Error('Pinned prior motion hash mismatch');inspectorBundle.motion.document=JSON.parse(new TextDecoder().decode(motionBytes));fillAssetMenu();await chooseAsset('human01');if(!currentAsset())return;
  try{const r=inspectorBundle.candidate,bytes=decodeAsset(r.data);if(await hashBytes(bytes)!==r.sha256)throw Error('Candidate source hash mismatch');const candidate=prepareAsset(bytes,r);verifyCandidateCompatibility(currentAsset(),candidate,r.compatibility,inspectorBundle.motion.document,inspectorBundle.motion);preparedAssets.set(r.id,candidate);ui$('asset').append(inspectorOption(r.id,r.label+' · '+r.version+' · proposed'));refreshReviewPolicy();refreshSource();}catch(e){reportInspector('Candidate unavailable; frozen original retained. '+e.message,true);}
  if(resourceGates.mode)inspectorRenderer=new StudioRenderer(ui$('view'));inspectorInitialized=true;inspectorClock=new RenderClock({raf:fn=>requestAnimationFrame(fn),cancel:id=>cancelAnimationFrame(id),now:()=>performance.now(),draw:drawInspector,onStop:reason=>{ui$('play').textContent='Play';reportInspector(reason);}});installInspectorEvents();syncInputFocus();if(Object.values(resourceGates).every(Boolean))inspectorClock.request();else inspectorClock.suspend('Ready; graphics suspended until visible and focused');
  window.rigInspectorDiagnostics={get state(){return {version:'private-animation-studio/rig-review-1',actorPlacement:currentPlacement(),soleMarkers:ui$('soleMarkers').checked,asset:currentAsset().record.id,hash:currentAsset().record.sha256,clip:activeClip()?.name||null,classification:activeClip()?.classification||null,time:currentTime,selectedNode,playing:inspectorClock.playing,active:inspectorClock.active,frames:inspectorClock.frames,rendererFrames:inspectorRenderer?.frames??0,pending:inspectorClock.pending,rendererAlive:!!inspectorRenderer,cachedModels:preparedAssets.size,candidateReviewOptIn:ui$('reviewOptIn').checked,modelGroup:modelReviewGroup(currentAsset().record),family:resolveFamilyMapping(currentAsset())?.family||null,clips:currentAsset().clips.map(c=>({id:c.id,name:c.name,classification:c.classification,duration:c.duration})),comparison:ui$('compare').value,gates:{...resourceGates},nodeCount:currentAsset().model.nodes.length,paletteCounts:currentAsset().model.skins.map(s=>s.joints.length),edits:structuredClone(localEdits)};}};
 }catch(e){pauseInspector('Initialization failed');reportInspector(e.message,true);}
}
function prunePreparedAssets(){const protectedIds=new Set(['human01','human01_skin_candidate_v1',currentAsset()?.record.id]);while(preparedAssets.size>6){const key=Array.from(preparedAssets.keys()).find(k=>!protectedIds.has(k));if(!key)break;preparedAssets.delete(key);}}
function releaseInspectorRenderer(){inspectorClock?.suspend('Viewport suspended');inspectorRenderer?.destroy();inspectorRenderer=null;}
function restoreInspectorRenderer(){if(inspectorInitialized&&resourceGates.mode&&resourceGates.context&&!inspectorRenderer){inspectorRenderer=new StudioRenderer(ui$('view'));inspectorClock?.request();}}
window.rigStudioControl={selectAsset:chooseAsset,selectClip:chooseClip,seek:seekInspector,setActive(value){if(!value){setResourceGate('mode',false,'Motion study selected');releaseInspectorRenderer();}else{resourceGates.mode=true;restoreInspectorRenderer();setResourceGate('mode',true);}},pause:pauseInspector,get ready(){return window.rigInspectorReady;}};
window.rigInspectorReady=initializeInspector();
