const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const assert = require("node:assert/strict");
const crypto = require("node:crypto");
const root = path.resolve(__dirname, "..");
const read = (name) =>
  JSON.parse(fs.readFileSync(path.join(root, name), "utf8"));
const standard = read("data/standard-benchmarks.original.json");
const notes = read("data/gallery-notes.json");
const catalog = read("data/catalog.original.json");
const originalResults = read("data/results.original.json");
const expected = {
  "hle-diamond": [59.9, 54.6, 53.2, 50.7, 33.3, 33.1, 32.8, 24.6, 22.8],
  "gpqa-diamond": [93, 88, 82.8, 81.6],
  "mmmu-pro": [81.2, 76.6, 66.1, 67.5],
  "swe-bench-pro-public-v1": [57.7, 54.4, 52.4, 45.7],
  "terminal-bench-2": [75.1, 60, 46.3, 38.2],
  "frontiermath-tier4-v2": [97.6, 83, 87.8, 90.2, 73.2],
};
function safeURL(url) {
  const u = new URL(url);
  assert.equal(u.protocol, "https:");
  assert.equal(u.username, "");
  assert.equal(u.password, "");
}
assert.equal(standard.schema_version, 1);
assert.equal(standard.researched_at, "2026-10-01");
assert.equal(standard.cards.length, 6);
assert.equal(
  standard.cards.reduce((n, c) => n + c.rows.length, 0),
  30,
);
assert.deepEqual(
  standard.cards.map((c) => c.id),
  Object.keys(expected),
);
for (const source of Object.values(standard.sources)) safeURL(source.url);
for (const c of standard.cards) {
  assert.equal(c.category, "standard");
  assert.equal(c.unit, "percent");
  assert.equal(c.direction, "higher_is_better");
  assert.deepEqual(c.scale, [0, 100]);
  assert.ok(standard.sources[c.source_id]);
  if (c.definition_source_id)
    assert.ok(standard.sources[c.definition_source_id]);
  assert.deepEqual(
    c.rows.map((r) => r.value),
    expected[c.id],
  );
  assert.equal(new Set(c.rows.map((r) => r.model_variant)).size, c.rows.length);
  for (const r of c.rows) {
    assert.ok(typeof r.model_variant === "string" && r.model_variant);
    assert.equal(r.cost_usd, null);
    assert.equal(r.latency_seconds, null);
    safeURL(r.source_url);
    assert.equal(r.source_url, standard.sources[c.source_id].url);
    if (c.id === "hle-diamond") {
      assert.equal(r.effort, "high");
      assert.ok(
        Math.abs((r.reasoning_percent + r.knowledge_percent) / 2 - r.value) <
          1e-10,
      );
    }
  }
}
assert.deepEqual(
  standard.cards[0].rows.map((r) => r.with_tools_percent),
  [82.9, 73.9, null, 72.3, 60.6, null, 65, 55.4, null],
);
assert.equal(
  standard.cards.filter((c) => c.display_status === "historical_source_cohort")
    .length,
  4,
);
const ids = [
  ...catalog.entries.map((e) => e.id),
  ...standard.cards.map((c) => c.id),
];
assert.equal(new Set(ids).size, 26);
assert.deepEqual(new Set(Object.keys(notes)), new Set(ids));
for (const id of ids) {
  assert.ok(notes[id].matters);
  assert.ok(notes[id].read);
}
assert.equal(originalResults.results.records.length, 18);
assert.equal(originalResults.graph_views.charts.length, 7);
for (const name of ["catalog.original.json", "results.original.json"]) {
  const actual = crypto
    .createHash("sha256")
    .update(fs.readFileSync(path.join(root, "data", name)))
    .digest("hex");
  const expectedHash =
    name === "catalog.original.json"
      ? "261e704c6076c5c85b698fefd9a4135d61049e56377d01d42c14aae28800ce85"
      : "dd9164301b95d503eda9f467fa6411e375b25e5ba0c9a3d9ec475e58ba3c68d3";
  assert.equal(actual, expectedHash, "Existing source bytes must be preserved");
}
const output = {
  standard,
  notes,
  provenance: {
    input:
      "Parent-supplied original public research JSON; no Library materialization",
    verification:
      "Primary HLE-Diamond, March OpenAI table, Astra FrontierMath row and Epoch v2 definition reopened on 2026-10-01",
    independentlyExecuted: false,
  },
};
const js =
  "/* Generated by scripts/build-gallery.cjs; preserve original source data. */\nwindow.LAB_GALLERY = " +
  JSON.stringify(output, null, 2)
    .replace(/</g, "\\u003c")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029") +
  ";\n";
fs.writeFileSync(path.join(root, "assets/gallery-data.js"), js);
const sandbox = { window: {} };
vm.runInNewContext(js, sandbox);
assert.deepEqual(
  JSON.parse(JSON.stringify(sandbox.window.LAB_GALLERY)),
  output,
);
fs.mkdirSync(path.join(root, "evidence"), { recursive: true });
fs.writeFileSync(
  path.join(root, "evidence/gallery-data-validation.json"),
  JSON.stringify(
    {
      checkedAt: new Date().toISOString(),
      cards: 26,
      standardRows: 30,
      existingResultRows: 18,
      existingCharts: 7,
      standardCostTime: "All 30 remain null",
      hleToolRows: 6,
      hleMissingToolRows: 3,
      unchangedOriginalHashes: true,
      passed: true,
    },
    null,
    2,
  ),
);
console.log(
  "Gallery input passed: 26 cards, 30 standard rows, original 18 rows and seven views unchanged.",
);
