// Bounded local smoke check: one headless browser, sequential contexts, no desktop control.
const assert=require('node:assert/strict');
const fs=require('node:fs');const path=require('node:path');const http=require('node:http');
const {pathToFileURL}=require('node:url');
const {chromium}=require(process.env.LAB_PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../..'),out=path.join(root,'evidence','lab-space');fs.mkdirSync(out,{recursive:true});
const report={testedAt:new Date().toISOString(),checks:[],screenshots:[],errors:[],externalRequests:[],accessibility:[],limits:'One sequential headless Edge smoke pass. Touch simulated. No real phone, assistive technology, desktop apps, sustained GPU/performance check, publication or catalog tests.'};
const done=name=>{report.checks.push(name);console.log('PASS '+name);};
const server=http.createServer((req,res)=>{let u=new URL(req.url,'http://127.0.0.1');const relative=u.pathname.replace(/^\/lab(?=\/|$)/,'');const file=path.resolve(root,'.'+(relative.endsWith('/')?relative+'index.html':relative));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.mjs':'text/javascript','.svg':'image/svg+xml'})[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));});
(async()=>{
 const nav=await import(pathToFileURL(path.join(root,'lab-space/assets/navigation.mjs')));
 for(const bad of ['javascript:alert(1)','constructor','__proto__','https://evil.example',null])assert.throws(()=>nav.safeDestination(bad));
 assert.equal(nav.safeDestination('catalog'),'https://pazneria.github.io/lab/');assert.equal(nav.safeDestination('home'),'https://pazneria.github.io/');done('Only exact public HTTPS destinations accepted');
 let p={x:0,z:1,yaw:0,pitch:0};for(let i=0;i<160;i++)nav.advance(p,new Set(['forward']),.05);assert(p.z>=-1.69);assert(!nav.blocked(p.x,p.z));
 p={x:5,z:0,yaw:0,pitch:0};for(let i=0;i<160;i++)nav.advance(p,new Set(['forward']),.05);assert(p.z>=-6.55);assert.equal(nav.nearby({x:.55,z:-.55}),'catalog');done('Bench collision, room boundary, reachable station');
 await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({channel:process.env.LAB_BROWSER_CHANNEL||'msedge',headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000}});const page=await ctx.newPage();
 page.on('pageerror',e=>report.errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith(base))report.externalRequests.push(r.url());});
 await page.goto(base+'/lab/lab-space/');await page.locator('#room').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#position').textContent.includes('north'));
 await page.screenshot({path:path.join(out,'lab-room-desktop.png'),fullPage:true});report.screenshots.push('lab-room-desktop.png');done('3D renders using /lab/ subpath and local vendor assets');
 const before=await page.locator('#map-player').getAttribute('transform');await page.locator('#room').focus();await page.keyboard.down('KeyW');await page.waitForTimeout(300);await page.keyboard.up('KeyW');assert.notEqual(await page.locator('#map-player').getAttribute('transform'),before);done('Keyboard walk updates room orientation');
 const rect=await page.locator('#room').boundingBox();const rotation=await page.locator('#map-player').getAttribute('transform');await page.mouse.move(rect.x+rect.width/2,rect.y+rect.height/2);await page.mouse.down();await page.mouse.move(rect.x+rect.width/2+90,rect.y+rect.height/2+10);await page.mouse.up();assert.notEqual(await page.locator('#map-player').getAttribute('transform'),rotation);done('Drag look updates camera');
 await page.locator('#visit-bench').click();await page.keyboard.press('Enter');assert(await page.locator('#station-dialog').isVisible());assert.equal(await page.locator('#dialog-link').getAttribute('href'),'https://pazneria.github.io/lab/');await page.keyboard.press('Escape');assert.equal(await page.evaluate(()=>document.activeElement.id),'room');done('Station keyboard interaction, exact catalog URL, modal focus return');
 await page.screenshot({path:path.join(out,'lab-room-bench.png'),fullPage:true});report.screenshots.push('lab-room-bench.png');
 const benchRect=await page.locator('#room').boundingBox();await page.mouse.click(benchRect.x+benchRect.width/2,benchRect.y+benchRect.height/2);assert(await page.locator('#station-dialog').isVisible());await page.keyboard.press('Escape');done('The actual 3D monitor opens the station on click');
 const walkUntil=async(key,condition)=>{await page.locator('#room').focus();await page.keyboard.down(key);try{await page.waitForFunction(condition,{},{timeout:7000});}finally{await page.keyboard.up(key);}};
 const clearPortal=()=>Number(document.querySelector('#map-player').getAttribute('transform').match(/translate\([^ ]+ ([\d.-]+)/)[1])<41.2;
 await walkUntil('KeyW',clearPortal);await walkUntil('KeyA',()=>document.querySelector('#position').textContent.includes('Apparatus bay'));
 await page.locator('#visit-bench').click();await walkUntil('KeyW',clearPortal);await walkUntil('KeyD',()=>document.querySelector('#position').textContent.includes('Study alcove'));
 assert(nav.blocked(3.6,-.6));assert(nav.blocked(5,-.6));assert(nav.blocked(7.4,-2.4));assert(!nav.blocked(3.6,-2.4));done('New apparatus bay and study portal reached by real keyboard input; pier, screen and desk colliders protect circulation');
 await page.locator('#reset').click();await page.keyboard.down('KeyD');await page.waitForTimeout(900);await page.keyboard.up('KeyD');assert.equal(await page.locator('#nearby').textContent(),'Exit to home');await page.keyboard.press('Enter');assert.equal(await page.locator('#dialog-link').getAttribute('href'),'https://pazneria.github.io/');await page.keyboard.press('Escape');done('Physical exit is reachable and opens the exact home destination');
 await page.locator('#reset').click();const stable=await page.locator('#map-player').getAttribute('transform');await page.keyboard.press('Tab');await page.keyboard.press('ArrowDown');assert.equal(await page.locator('#map-player').getAttribute('transform'),stable);done('Navigation keys only captured by focused canvas');
 if(process.env.LAB_AXE_SCRIPT){await page.addScriptTag({path:process.env.LAB_AXE_SCRIPT});const a=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));});report.accessibility.push({mode:'desktop 3D',violations:a});assert.deepEqual(a,[]);done('Desktop automated WCAG A/AA check');}
 await page.locator('#mode').click();assert(await page.locator('#flat-view').isVisible());await page.locator('#mode').click();await page.evaluate(()=>document.querySelector('#room').dispatchEvent(new Event('webglcontextlost',{cancelable:true})));assert(await page.locator('#flat-view').isVisible());assert(await page.locator('.station .primary').isVisible());done('Manual flat switch and WebGL context loss retain real tools');await ctx.close();
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const m=await mobile.newPage();await m.goto(base+'/lab/lab-space/');await m.locator('#room').waitFor({state:'visible'});await m.screenshot({path:path.join(out,'lab-room-mobile-entrance.png'),fullPage:true});report.screenshots.push('lab-room-mobile-entrance.png');await m.locator('#visit-bench').tap();const start=await m.locator('#map-player').getAttribute('transform');await m.locator('[data-move="right"]').tap();assert.notEqual(await m.locator('#map-player').getAttribute('transform'),start);await m.locator('#nearby').tap();assert(await m.locator('#station-dialog').isVisible());await m.locator('.close').tap();assert(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await m.evaluate(()=>scrollTo(0,0));const pad=await m.locator('#movement').boundingBox(),room=await m.locator('#room').boundingBox();assert(pad.y>=room.y&&pad.y+pad.height<=room.y+room.height);await m.screenshot({path:path.join(out,'lab-room-mobile.png'),fullPage:true});report.screenshots.push('lab-room-mobile.png');done('Mobile touch controls stay over visible room; station tap and 390px reflow');
 if(process.env.LAB_AXE_SCRIPT){await m.addScriptTag({path:process.env.LAB_AXE_SCRIPT});const a=await m.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return r.violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)}));});report.accessibility.push({mode:'mobile 3D',violations:a});assert.deepEqual(a,[]);}await mobile.close();
 const reduced=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});const r=await reduced.newPage();await r.goto(base+'/lab/lab-space/');assert(await r.locator('#flat-view').isVisible());assert(await r.locator('#gentle').isChecked());await r.screenshot({path:path.join(out,'lab-room-flat.png'),fullPage:true});report.screenshots.push('lab-room-flat.png');await r.locator('#mode').click();await r.locator('#room').waitFor({state:'visible'});done('Reduced motion starts flat; 3D is deliberate and gentle');await reduced.close();
 const unsupported=await browser.newContext();const u=await unsupported.newPage();await u.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.startsWith('webgl')?null:original.call(this,type,...args);};});await u.goto(base+'/lab/lab-space/');await u.waitForFunction(()=>document.querySelector('#flat-message').textContent.includes('unavailable'));assert(await u.locator('.station .primary').isVisible());done('WebGL unavailable starts safe flat fallback');await unsupported.close();
 const nojs=await browser.newContext({javaScriptEnabled:false});const n=await nojs.newPage();await n.goto(base+'/lab/lab-space/');assert(await n.locator('#flat-view').isVisible());assert.equal(await n.locator('.station .primary').getAttribute('href'),'https://pazneria.github.io/lab/');done('JavaScript off retains room plan and native catalog/home links');await nojs.close();
 assert.deepEqual(report.errors,[]);assert.deepEqual(report.externalRequests,[]);done('No page errors or external asset requests');
 }finally{await browser.close();}
 report.status='passed';
})().catch(e=>{report.status='failed';report.failure=e.stack;console.error(e);process.exitCode=1;}).finally(()=>{fs.writeFileSync(path.join(out,'validation.json'),JSON.stringify(report,null,2));server.close();});
